apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-pv0001
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /var/export/gogs
    server: ose3-master.example.com

